name: widgetbook_workspace
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.21.0
  widgetbook_annotation: ^3.10.0
  hostr:
    path: ../
  hostr_sdk:
    path: ../../hostr_sdk
  models:
    path: ../../models
  web3dart: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.21.0
  build_runner: ^2.11.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mockito: ^5.6.3


flutter:
  uses-material-design: true

dependency_overrides:
  intl: ^0.20.2
