name: widgetbook_workspace
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  flutter_bloc: ^9.0.0
  chopper: ^8.0.0
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 
  models: 
    path: ../../models
  hostr_sdk: 
    path: ../../hostr_sdk
  hostr:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.11.0
  build_runner: ^2.4.9
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mockito: ^5.4.4


flutter:
  uses-material-design: true
