databasePath: data/sqlite.db

dashboard:
  enabled: true
  username: admin
  password: "${BLOSSOM_DASHBOARD_PASSWORD}"

discovery:
  nostr:
    enabled: false
    relays: []
  upstream:
    enabled: false

storage:
  backend: local
  removeWhenNoOwners: false
  local:
    dir: ./data/blobs
  rules:
    - type: text/*
      expiration: 1 month
    - type: "image/*"
      expiration: 10 years
    - type: "video/*"
      expiration: 10 years
    - type: "model/*"
      expiration: 1 week
    - type: "*"
      expiration: 2 days

upload:
  enabled: true
  requireAuth: false
  requirePubkeyInRule: false

media:
  enabled: true
  requireAuth: true
  requirePubkeyInRule: false
  image:
    quality: 100
    progressive: true
    maxWidth: 19200
    maxHeight: 10800
    outputFormat: "webp"
    maintainAspectRatio: true
    keepExif: true
    fps: 30
  video:
    quality: 100
    maxHeight: 1080
    maxFps: 30
    format: "webm"
    audioCodec: "aac"
    videoCodec: "libx264"

list:
  requireAuth: false
  allowListOthers: true

tor:
  enabled: false
  proxy: ""
