# Nostr-rs-relay configuration (staging)

[info]
relay_url = "wss://relay.staging.hostr.network/"
name = "Hostr relay (staging)"
description = "Hostr staging relay."

[network]
address = "0.0.0.0"
port = 80

[options]
reject_future_seconds = 1800

[limits]
limit_scrapers = false
