# Nostr-rs-relay configuration (development/test)

[info]
relay_url = "wss://relay.hostr.development/"
name = "Hostr relay (development)"
description = "Hostr development/test relay."

[network]
address = "0.0.0.0"
port = 80

[options]
reject_future_seconds = 1800

[limits]
limit_scrapers = false
