name: hostr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  auto_route: ^11.1.0
  get_it: ^9.2.0
  bech32: ^0.2.2
  bolt11_decoder: ^1.0.2
  injectable: ^2.7.1+4
  validators: ^3.0.0
  flutter_secure_storage: ^10.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.14.2
  sliding_up_panel: ^2.0.0+1
  hydrated_bloc: ^10.1.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  carousel_slider: ^5.1.2
  timeago: ^3.7.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  convert: ^3.1.2
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  web3dart: ^3.0.2
  wallet: ^0.0.18
  logger: ^2.6.2
  http: ^1.6.0
  dio: ^5.9.1
  intl: ^0.20.2
  uuid: ^4.5.2
  # NIP04 deps
  pointycastle: ^4.0.0
  crypto: ^3.0.7
  chopper: ^8.5.0
  json_annotation: ^4.10.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  models:
    path: ../models
  hostr_sdk:
    path: ../hostr_sdk
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 
  workmanager: ^0.9.0+3
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.1.0
  date_count_down: ^4.0.0
  timelines_plus: ^1.0.8
    
dev_dependencies:
  mockito: ^5.6.3
  auto_route_generator: ^10.4.0
  injectable_generator: ^2.12.0
  build_runner: ^2.11.1 
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.12.0
  integration_test:
    sdk: flutter
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  flutter_driver:
    sdk: flutter
  mocktail_image_network: ^1.2.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

dependency_overrides:
  intl: ^0.20.2