name: hostr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  auto_route: ^11.1.0
  get_it: ^9.2.0
  bech32: ^0.2.2
  bolt11_decoder: ^1.0.2
  injectable: ^2.5.0
  validators: ^3.0.0
  flutter_secure_storage: ^10.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  sliding_up_panel: ^2.0.0+1
  hydrated_bloc: ^10.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  carousel_slider: ^5.0.0
  timeago: ^3.2.2
  path_provider: ^2.1.1
  rxdart: ^0.28.0
  convert: ^3.0.1
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.14.2
  web3dart: ^3.0.1
  wallet: ^0.0.18
  logger: ^2.5.0
  http: ^1.2.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  uuid: ^4.5.1
  # NIP04 deps
  pointycastle: ^4.0.0
  crypto: ^3.0.6
  chopper: ^8.0.0
  json_annotation: ^4.9.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  image_picker: ^1.1.2
  models:
    path: ../models
  hostr_sdk:
    path: ../hostr_sdk

    # @TODO: Remove this dependency and use hostr_sdk instead
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 
    
dev_dependencies:
  mockito: ^5.4.5
  auto_route_generator: ^10.4.0
  injectable_generator:  
  build_runner: ^2.4.9 
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2
  integration_test:
    sdk: flutter
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  flutter_driver:
    sdk: flutter
  mocktail_image_network: ^1.2.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/