name: hostr_sdk
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  get_it: ^9.2.0
  models:
    path: ../models
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 
  injectable: ^2.7.1+4
  rxdart: ^0.28.0
  logger: ^2.6.2
  web3dart: ^3.0.2
  equatable: ^2.0.8
  wallet: ^0.0.18
  bolt11_decoder: ^1.0.2
  http: ^1.6.0
  hydrated_bloc: ^10.1.1
  chopper: ^8.5.0
  bloc: ^9.2.0

dev_dependencies:
  build_runner: ^2.11.0
  chopper_generator: ^8.6.0
  injectable_generator: ^2.12.0
  lints: ^6.0.0
  mockito: ^5.6.3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  swagger_dart_code_generator: ^4.1.1
  test: ^1.25.6
  web3dart_builders: ^3.0.1

dependency_overrides:
  # Keep other overrides
  web3dart_builders: 
    git:
      url: https://github.com/PatrickGeyer/web3dart_builders.git
      ref: feat/upgrade-deps