name: models
description: Models for nostr based accommodation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  web3dart: ^3.0.2
  convert: ^3.1.2
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 
  faker: ^2.2.0
  crypto: ^3.0.7
  logger: ^2.6.2
  h3_dart: ^0.7.0

dependency_overrides:
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.29.0