name: models
description: Models for nostr based accommodation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  web3dart: ^3.0.1
  convert: ^3.0.1
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 
  smart_faker: ^0.4.0

dev_dependencies:
  test: ^1.25.6