name: models
description: Models for nostr based accommodation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  web3dart: ^3.0.2
  convert: ^3.1.2
  ndk:
    git:
      url: https://github.com/relaystr/ndk.git 
      path: packages/ndk 

dependency_overrides:
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.29.0